return {
	{ '559168017523539968', ':robot:', 'The Bot can manage the whole server and see every channel to provided the necessary support to the members.\n\nThis role can not be assigned to other bots.', { }, { 'Server Manager' } },
	{ '462279926532276225', '<:wheel:456198795768889344'..'>', 'Module Members have the objective of helping developers and funcorps with the Transformice\'s special functions, besides handling server modules and providing support about their own modules.', { 'Must be part of the official Module Team' }, { 'Upload module images', 'Make maps permanent in specific categories', 'Create/delete global commands', 'Create/delete server modules', 'Developer role', 'Access to all global commands' } },
	{ '462281046566895636', '<:lua:468936022248390687'..'>', 'Developers have the objective of helping other members in the #script-requests channel or in any problem where programming is needed. They can also support a variety of different programming languages, such as C and Python.', { 'Must know Lua', 'Have at least one good module (official, semi-official, or unofficial) published on forums' }, { 'Load Lua scripts in the server', 'Access to the channel <#462279117866401792>', 'Access to global commands level 2' } },
	{ true, '462285151595003914', '<:p5:468937377981923339'..'>', 'Artists have the objective of helping other members with things related to art, such as line styles or even photoshop.', { '`[optional]` Have a FanArt gallery published on forums', '`[optional]` Have any previous work added in the game (furs, items, in modules, etc)', '`[optional]` Have great off-topic drawings', '`[optional]` Be proficient in image edition' }, { } },
	{ '494665355327832064', ':earth_americas:', 'Translators have the objective of helping with content translations, from forum threads to big modules and events.', { '`[autohire]` Currently are, or was part of the Official Translators Team', '`[autohire]` Currently are, or was part of the [Translators Team](https://discord.gg/mMre2Dz)', 'Must speak intermediary+ English', 'Must have previously translated something to Transformice (module threads, modules, events, game lines).' }, { 'Special display when online at /room #bolodefchoco' } },
	{ true, '462329326600192010', '<:p41:463508055577985024' .. '>', 'Mappers have the objective of helping other members in the <#559089568411025430> channel or in any problem where maps are involved, including tips of how to improve one\'s map.', { '`[optional]` Have at least one high-perm map (P3 to P10 or P24)', '`[optional]` Review maps in a module that has a topic in the [Map Submissions](https://atelier801.com/section?f=6&s=102) forum' }, { 'Access to the channel <#462279117866401792>' } },
	{ '481189370448314369', '<:idea:559070151278854155' .. '>', 'Event Managers have the objective of helping other members that are planning an event, giving support on programmation, art or ideas.', { 'Must be working, or have worked on an official event. (Coding, drawing, giving ideas, etc)' }, { } },
	{ '544202727216119860', '<:illuminati:542115872328646666' .. '>', 'Shades Helpers have the objective of helping other people in the #help and #lua chats in Transformice.', { 'Be active in the chat #help and/or #lua on Transformice', 'Have similar concepts about the use of those chats compared to the rest of the team', 'Be cooperative in the server, helping others whenever possible' }, { 'Access to the commands of the bot <@545376143365373996>', 'Access to chats in Transformice through discord' } },
	{ '526822896987930625', '<:fun:559069782469771264' .. '>', 'Funcorps have the objective of aiding members whenever possible, from hosting their images to scheduling event rooms.', { 'Must be part of the official Funcorp team' }, { 'Upload module images', 'Special channel to contact the Module Team' } },
	{ '514913541627838464', ':triangular_ruler:', 'Mathematicians should aim to help other members in <#512243074198405120> or in any situation that involves anything related to mathematics and physics.', { '`[autohire]` Study any exact-science course.', 'Help other members whenever possible with anything related to mathematics and physics' }, { } },
	{ '465631506489016321', '<:dance:468937918115741718' .. '>', 'Fashionistas have the objective of helping other members with design, especially Transformice outfits.', { '`[autohire]` Currently are, or was part of the official Fashion Squad', 'Have good outfits published on forums or ingame' }, { } },
	{ true, '514913155437035551', ':pencil:', 'Writers have the objective of helping other members with writing stories, scripts and plots.', { '`[optional]` Have at least one FanFic on forums with at least 5 comments from other users', '`[optional]` Have a story or book published out of forums' }, { } }
}
